##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: An Archive of Rodolfo Vera Quizon Sr. 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: Honoring the King of Comedy: The Complete Archive of Dolphy
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "Rodolfo Vera Quizon Sr., widely known as the “King of Comedy” in the Philippines, built a legacy that transformed Filipino entertainment through decades of film, television, and stage performances. Starting from humble beginnings, he rose to fame by portraying relatable, heartfelt, and humorous characters that reflected the everyday lives of ordinary Filipinos. His unique blend of natural wit, timing, and emotional depth made him not just a comedian, but a storyteller who captured both laughter and life lessons in every role.
Throughout his career, Dolphy became a cultural icon whose influence shaped generations of actors and comedians. His body of work showed that comedy could also carry sincerity, social insight, and humanity. Because of his outstanding contribution to Philippine arts and culture, he was among the distinguished artists honored with one of the nation’s highest civilian recognitions, the Grand Collar of the Order of the Golden Heart, symbolizing his service and impact on Filipino society.
From stage to screen, Dolphy’s journey was not just about fame—it was an “adventure” of perseverance, passion, and purpose. His dedication to his craft and his ability to make people laugh even during difficult times earned him the enduring title King of Comedy, a name that continues to define excellence in Philippine entertainment long after his passing."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: RHOB AVIEL Y. SIBAL

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: demo-metadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "Center for Digital Inquiry and Learning (CDIL)"
# organization-link: https://cdil.lib.uidaho.edu/
# organization-logo-banner: https://cdil.lib.uidaho.edu/storying-extinction/assets/img/cdil.png
# organization-logo-nav: https://cdil.lib.uidaho.edu/assets/img/logo.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
